# Generated by Django 5.1.3 on 2024-11-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='major_skill_category',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='logo',
            new_name='imagem_inicio',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='descricao',
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='resumo',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='MajorSkillCategory',
        ),
    ]
