# Generated by Django 5.1.3 on 2024-11-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_remove_skillcategory_ativo_skill_pos_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='imagem_central',
            field=models.ImageField(blank=True, null=True, upload_to='skills/imagem_central'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='imagem_inicio',
            field=models.ImageField(blank=True, null=True, upload_to='skills/logos'),
        ),
    ]
