# Generated by Django 5.1.3 on 2024-11-26 19:00

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skill_imagem_central_alter_skill_imagem_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibilidadeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='imagem_central',
        ),
        migrations.AddField(
            model_name='skill',
            name='code_example_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='code_example_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='descricao_1',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='descricao_1'),
        ),
        migrations.AddField(
            model_name='skill',
            name='descricao_2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='descricao_2'),
        ),
        migrations.AddField(
            model_name='skill',
            name='descricao_3',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='descricao_3'),
        ),
        migrations.AddField(
            model_name='skill',
            name='extensao_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='iframe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='imagem_1',
            field=models.ImageField(blank=True, null=True, upload_to='skills/imagens'),
        ),
        migrations.AddField(
            model_name='skill',
            name='imagem_2',
            field=models.ImageField(blank=True, null=True, upload_to='skills/imagens'),
        ),
        migrations.AddField(
            model_name='skill',
            name='imagem_3',
            field=models.ImageField(blank=True, null=True, upload_to='skills/imagens'),
        ),
        migrations.AddField(
            model_name='skill',
            name='progress_bar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='titulo_descricao_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='titulo_descricao_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='titulo_descricao_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='possibilidades',
            field=models.ManyToManyField(blank=True, related_name='possibilidades', to='skills.possibilidadeskills'),
        ),
    ]
