# Generated by Django 5.1.3 on 2024-11-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_possibilidadeskills_remove_skill_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
