# Generated by Django 5.1.3 on 2024-11-15 16:25

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0002_remove_skillcategory_major_skill_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('resumo', models.TextField(blank=True)),
                ('imagem_inicio', models.ImageField(blank=True, upload_to='projeto/start')),
                ('link_github', models.CharField(blank=True, max_length=255)),
                ('link_demo', models.CharField(blank=True, max_length=255)),
                ('imagem_central', models.ImageField(blank=True, upload_to='projeto/imagem_central')),
                ('descricao', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='descricao')),
                ('ativo', models.BooleanField(default=True)),
                ('pos_destaque', models.IntegerField(blank=True, default=5, null=True)),
                ('iframe', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('skills', models.ManyToManyField(blank=True, related_name='projeto', to='skills.skill')),
            ],
        ),
    ]
