# Generated by Django 5.1.3 on 2024-11-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='name',
            new_name='nome',
        ),
    ]
