# Generated by Django 5.1.3 on 2024-11-16 00:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_rename_name_projeto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
