# Generated by Django 5.1.3 on 2024-11-23 23:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_projeto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='imagem_central',
        ),
        migrations.AddField(
            model_name='projeto',
            name='categoria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='cliente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_fim',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_inicio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem_galeria_1',
            field=models.ImageField(blank=True, upload_to='projeto/imagem_galeria'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem_galeria_2',
            field=models.ImageField(blank=True, upload_to='projeto/imagem_galeria'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem_galeria_3',
            field=models.ImageField(blank=True, upload_to='projeto/imagem_galeria'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem_galeria_4',
            field=models.ImageField(blank=True, upload_to='projeto/imagem_galeria'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='texto',
            field=django_ckeditor_5.fields.CKEditor5Field(default='dasd', verbose_name='descricao'),
            preserve_default=False,
        ),
    ]
