# Generated by Django 5.1.3 on 2024-11-23 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_remove_projeto_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='categoria_projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='projetos.categoriaprojeto'),
        ),
    ]
