# Generated by Django 5.1.3 on 2024-11-24 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_categoriaprojeto_projeto_categoria_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaprojeto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='categoria_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='projetos.categoriaprojeto'),
        ),
    ]
