# Generated by Django 5.1.3 on 2024-11-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_categoriaprojeto_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem_inicio',
            field=models.ImageField(blank=True, null=True, upload_to='projeto/start'),
        ),
    ]
